clear all;
close all;
%%
load('realnasim');
load('modelrez');
figure;
subplot(2,1,1);
plot(out.time,out.vhod,'b');
title('Vzbujanje');
xlabel('t[s]');
ylabel('U[V]');
grid on;
hold on;
subplot(2,1,2);
plot(out.izhod.time,out.izhod.data,'b',out1.fi.time,rad2deg(out1.fi.data),'g' );
title('Odziv');
xlabel('t[s]');
ylabel('fi[°]');
grid on;
legend("Odziv realne naprave", "Odziv nelinearnega modela","Location","SouthEast");
% load('modelrez');
% figure;
% subplot(2,1,1);
% plot(out1.time,out1.U,'b');
% title('vzbujanje');
% xlabel('t[s]');
% ylabel('U[V]');
% grid on;
% hold on;
% subplot(2,1,2);
% plot(out1.fi.time,rad2deg(out1.fi.data),'r');
% grid on;